#!/bin/bash
set -euf -o pipefail

if [ "$TRAVIS_JOB" = "test" ]; then
    sudo apt-get install -y $(cat esp/packages_base.txt | grep -v ^memcached | grep -v ^postgres | grep -v ^libpq-dev)
    sudo apt-get install postgresql-server-dev-9.1
    esp/packages_base_manual_install.sh
    pip install -r esp/requirements.txt
elif [ "$TRAVIS_JOB" = "lint" ]; then
    pip install flake8
else
    echo "Unknown TRAVIS_JOB: $TRAVIS_JOB"
    exit 1
fi
